### ISSUE TITLE
Fix the plugin ID

### ISSUE THREAD

**Issue by chloe-the-catgirl** [ItsVipra/ProToots#6]
The ID is currently set to `protoots@mastodon.com`, which was chosen as a placeholder. We definitely should change that asap.

**Comment by ItsVipra** [comment]
some suggestions:
`protoots@fedi.tools`
`protoots@trans.rights`
`protoots@mastodon.extension`
`protoots@fedi.extension`

---
Honestly I like `protoots@trans.rights` a lot :D
[The ID doesn't need to be an actual email address, just have the format of one](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/browser_specific_settings#extension_id_format), so that should work.

**Comment by chloe-the-catgirl** [comment]
+1 for the trans.rights idea. ^^
